version: 2

models:
  - name: fact_user_sessions
    description: Session facts at the user level
    columns:
      - name: user_id
        description: user_id
        tests:
          - unique
          - not_null

  - name: fact_product_sessions
    description: Session facts at th product level
    columns:
      - name: product_id
        description: product_id
        tests:
          - unique
          - not_null