version: 2

models:
  - name: fact_user_sessions
    description: Session facts at the user level
    columns:
      - name: user_id
        description: user_id
        tests:
          - unique
          - not_null